### ISSUE TITLE
Setting a default encoding when original encoding is not supported

### ISSUE THREAD

**Issue by aameyer** [Sicos1977/MSGReader#167]
I'm trying to open an eml file with the body encoded as "unknown-8bit":

...
MIME-Version: 1.0
...
Content-Type: text/plain; charset="unknown-8bit"
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
...

This results in an error while calling the constructor, as this encoding is not supported. Outlook opens the file just fine.

Would it be possible to have a default encoding to fall back to in cases like this? I understand this might result in nonsense if the eml is encoded using some radically different encoding, but in this case I am safe to assume some default - maybe make it an optional parameter?

**Comment by Sicos1977** [comment]
Could you send me the eml file that is doing this. I want to figure out what Outlook is doing. If so then please send it to sicos2002@hotmail.com

**Comment by sarathbabuk** [comment]
i also has the same problem, my eml file has encoding with "x-user-defined", and it failed to load. below exception message is returned while loading the eml file into MsgReader class.

System.ArgumentException: 'x-user-defined' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name 
   at System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
   at System.Globalization.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at MsgReader.Mime.Decode.EncodingFinder.FindEncoding(String characterSet)
   at MsgReader.Mime.Decode.EncodedWord.Decode(String encodedWords)
   at MsgReader.Mime.Header.HeaderFieldParser.ParseContentType(String headerValue)
   at MsgReader.Mime.Header.MessageHeader.ParseHeader(String headerName, String headerValue)
   at MsgReader.Mime.Header.MessageHeader.ParseHeaders(NameValueCollection headers)
   at MsgReader.Mime.Header.MessageHeader..ctor(NameValueCollection headers)
   at MsgReader.Mime.Header.HeaderExtractor.ExtractHeadersAndBody(Byte[] fullRaw Message, MessageHeader& headers, Byte[]& body)
   at MsgReader.Mime.MessagePart.ParseMultiPartBody(Byte[] rawBody)
   at MsgReader.Mime.MessagePart.ParseBody(Byte[] rawBody)
   at MsgReader.Mime.MessagePart..ctor(Byte[] rawBody, MessageHeader headers)
   at MsgReader.Mime.Message..ctor(Byte[] rawMessageContent, Boolean parseBody)
   at MsgReader.Mime.Message.Load(Stream messageStream)
   at MsgReader.Mime.Message.Load(FileInfo file)

Sarath.

**Comment by sarathbabuk** [comment]
we were receiving files with content transfer encoding "uuencode", MsgReader is not able to extract the file properly.  we were not able to open attachment and observed that the size is different from the attachment to extracted file.
"Content-Transfer-Encoding: uuencode"

**Comment by aameyer** [comment]
eml file sent. My call stack ends at the same System.ArgumentException as sarathbabuk's comment.

**Comment by sarathbabuk** [comment]
i had modified the code to send default encoding as "utf-8". in "EncondingFinder.cs" file "FindEncoding" method in the catch block "if (FallbackDecoder == null)" this has "throw", i had removed the throw and added "return Encoding.GetEncoding("utf-8"); " this will return "utf-8" when ever there is any argument exception.

**Comment by sarathbabuk** [comment]
sicos1977 has to confirm that above change is appropriate.

**Comment by Sicos1977** [comment]
I agree with the change. Is it possible to send me a pull request for it?

**Comment by sarathbabuk** [comment]
i am not ablet to add pull request
[EncodingFinder.zip](https://github.com/Sicos1977/MSGReader/files/3554637/EncodingFinder.zip)

**Comment by Sicos1977** [comment]
Added in commit a81601083feeecca61411ab6a8ccdaa9a1fa442a
