### ISSUE TITLE
ArgumentException opening a specific MSG-file (appointment)

### ISSUE THREAD

**Issue by rboen** [Sicos1977/MSGReader#219]
**Describe the bug**
While creating a message instance of the attached msg-File via Storage.Message(stream) a ArgumentException is raised.

System.ArgumentException: Destination array was not long enough.
Check destIndex and length, and the array's lower bounds.

 at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at MsgReader.Outlook.Storage.MapiTagMapper.GetMapping(IEnumerable`1 propertyIdents)
 at MsgReader.Outlook.Storage.Message.LoadStorage(CFStorage storage)

**Additional context**

**Comment by rboen** [comment]
[TEst (2).zip](https://github.com/Sicos1977/MSGReader/files/4877849/TEst.2.zip)

**Comment by Sicos1977** [comment]
This packages fixes your error --> https://www.nuget.org/packages/MSGReader/3.7.26
