### ISSUE TITLE
New Version 4.4.3 ImageSharp.UnknownImageFormatException

### ISSUE THREAD

**Issue by Zoidster** [Sicos1977/MSGReader#298]
**Describe the bug**
In one of our UnitTests we now get a SixLabors.ImageSharp.UnknownImageFormatException on parsing an msg file with a rtf formatted body.
With version 4.3.2 this was not an issue.

**To Reproduce**
Using the test msg file in [20 Testdokument Zeile 20.zip](https://github.com/Sicos1977/MSGReader/files/8409091/20.Testdokument.Zeile.20.zip) we use a simple `new Storage.Message(MsgWithRtfBody);`

**Expected behavior**
The expected behavior is that the created message object has a filled BodyRtf property

**Stacktrace**
```c#
SixLabors.ImageSharp.UnknownImageFormatException
Image cannot be loaded. Available decoders:
 - BMP : BmpDecoder
 - TGA : TgaDecoder
 - JPEG : JpegDecoder
 - GIF : GifDecoder
 - PNG : PngDecoder
 - Webp : WebpDecoder
 - TIFF : TiffDecoder
 - PBM : PbmDecoder

   at SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Load(Stream stream)
   at MsgReader.Outlook.Storage.Attachment.SaveImageAsPng(Int32 bufferOffset)
   at MsgReader.Outlook.Storage.Attachment..ctor(Storage message, String storageName)
   at MsgReader.Outlook.Storage.Message.LoadAttachmentStorage(CFStorage storage, String storageName)
   at MsgReader.Outlook.Storage.Message.LoadStorage(CFStorage storage)
   at MsgReader.Outlook.Storage..ctor(String storageFilePath, FileAccess fileAccess)
   at MsgReader.Outlook.Storage.Message..ctor(String msgfile, FileAccess fileAccess)
```

**Used Target Framework**
net6.0

**Comment by Zoidster** [comment]
Thanks!

**Comment by Sicos1977** [comment]
I would suggest to revert back to previous version as a temporary solution, it should work fine with .net 6.0 but gives reference errors with lower .NET versions because of a bug in MUAI

**Comment by Sicos1977** [comment]
I looked into the issue it seems it is failing on a BMP image. I also tested it with some other BMP files and those are working fine. So it is something in the ImageSharp decoder that does not like it. 

This is something I can't fix and it is better that you make an issue at the ImageSharp repository.

**Comment by Sicos1977** [comment]
Fixed in the latest nuget package
