### ISSUE TITLE
Problem with BodyHtml property when message format is RTF

### ISSUE THREAD

**Issue by bilki** [Sicos1977/MSGReader#31]
Hello Kees,

I'm having a problem when accessing the BodyHtml property in Outlook.Storage.Message class.

If the email format is RTF,  like this one written and sent with Outlook 2010: [broken_rtf.zip](https://github.com/Sicos1977/MSGReader/files/191671/broken_rtf.zip) I get the following exception:

`--NullReferenceException
at MsgReader.Rtf.DomDocument.Load(Reader reader, DocumentFormatInfo parentFormat) in C:\Users\Kees\Documents\GitHub\MsgReader\MsgReader\Rtf\DomDocument.cs:line 1466
at MsgReader.Rtf.DomDocument.Load(Reader reader, DocumentFormatInfo parentFormat) in C:\Users\Kees\Documents\GitHub\MsgReader\MsgReader\Rtf\DomDocument.cs:line 367
at MsgReader.Rtf.DomDocument.LoadRtfText(String rtfText) in C:\Users\Kees\Documents\GitHub\MsgReader\MsgReader\Rtf\DomDocument.cs:line 293
at MsgReader.Outlook.Storage.Message.get_BodyHtml() in C:\Users\Kees\Documents\GitHub\MsgReader\MsgReader\Outlook\Message.cs:line 1066`

I tried to debug it by myself, but I don't have enough knowledge about RTF to know what is happening here.

**Comment by Sicos1977** [comment]
Hi,

The error you encountered should be fixed now. Just get the latest code from Github

Greetings,
Kees van Spelde

**Comment by bilki** [comment]
Thank you Kees.

Just one more question. When will it be available on nuget?

**Comment by Sicos1977** [comment]
It should be there now
