### ISSUE TITLE
Exception is thrown when converting (some of the) .msg file to HTML that contains ==> symbol 

### ISSUE THREAD

**Issue by EugineD** [Sicos1977/MSGReader#316]
When calling:

var reader = new MsgReader.Reader();
files = reader.ExtractToFolder(
                  inputFile,
                  outputFolder,
                  messageType: MsgReader.Outlook.MessageType.Email);

for the .msg file with "==>" symbol next exception is thrown: 

System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at RtfPipe.Model.FieldParser.ParseSymbol(IList`1 args, IEnumerable`1 styles)
   at RtfPipe.Model.Builder.Build(List`1 body, Document document, List`1 defaultStyles)
   at RtfPipe.Model.Builder.Build(Document document)
   at RtfPipe.Rtf.ToHtml(RtfSource source, XmlWriter writer, RtfHtmlSettings settings)
   at RtfPipe.Rtf.ToHtml(RtfSource source, RtfHtmlSettings settings)
   at MsgReader.Outlook.RtfToHtmlConverter.ConvertRtfToHtml(String rtf)
   at MsgReader.Reader.PreProcessMsgFile(Message message, ReaderHyperLinks hyperlinks, String outputFolder, String& fileName, Boolean& htmlBody, String& body, String& contactPhotoFileName, List`1& attachments, List`1& files)
   at MsgReader.Reader.WriteMsgEmail(Message message, String outputFolder, ReaderHyperLinks hyperlinks)
   at MsgReader.Reader.ExtractToFolder(String inputFile, String outputFolder, ReaderHyperLinks hyperlinks, Nullable`1 messageType, Stream logStream)
   at ConsoleApp1.MsgReaderExtraction.Extract(String inputFile) in D:\repo\dev.jennydronova\msgReaderTest\MsgReaderTest\ConsoleApp1\MsgReaderExtraction.cs:line 18

[b.zip](https://github.com/Sicos1977/MSGReader/files/10034694/b.zip)

**Comment by Sicos1977** [comment]
I can't fix this bug because it is happening in another library that is not made by me. Best to raise an issue overhere --> https://github.com/erdomke/RtfPipe/issues
