### ISSUE TITLE
Large EML File Reading Error

### ISSUE THREAD

**Issue by DisIsAbhi** [Sicos1977/MSGReader#361]
When i try to Parse an EML file with 2.75GB size using 
var finfo = new FileInfo(_fileName);
				using var strm = finfo.Open(FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
				_eml = Message.Load(strm);

I get the following Error. 
Array dimensions exceeded supported range.
StackTrace: - 
   at Microsoft.IO.RecyclableMemoryStream.ToArray() in /_/src/RecyclableMemoryStream.cs:line 840
   at MsgReader.Mime.Message.Load(Stream messageStream)

**Comment by Sicos1977** [comment]
You can overload the RecyclableMemoryStream throught this class `https://github.com/Sicos1977/MSGReader/blob/master/MsgReaderCore/Helpers/StreamHelpers.cs` . You probably need to set a new memorystream manager so that it fits your very large files.
