### ISSUE TITLE
GetEmailRecipientsRfc822Format() method throws a System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by kostelis** [Sicos1977/MSGReader#400]
When reading the recipients using this method `message.GetEmailRecipientsRfc822Format(RecipientType.To)` from an MSG file that is an invitation to an appointment, the MSGReader throws an exception: 

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MsgReader.Outlook.RecipientRow..ctor(BinaryReader binaryReader, AddressType addressType, Boolean supportsRtf, Boolean displayNameIncluded, Boolean emailAddressIncluded, Boolean addressTypeIncluded, Boolean simpleDisplayNameIncluded, Boolean transmittableDisplayNameSameAsDisplayName, Boolean transmittableDisplayNameIncluded, Boolean stringsInUnicode)
   at MsgReader.Outlook.UnsendableRecipients..ctor(Byte[] data)
   at MsgReader.Outlook.Storage.GetUnsendableRecipients(String propIdentifier)
   at MsgReader.Outlook.Storage.Appointment..ctor(Storage message)
   at MsgReader.Outlook.Storage.Message.get_Appointment()
   at MsgReader.Outlook.Storage.Message.GetEmailRecipientsRfc822Format(RecipientType type)
```

**To Reproduce**
Create a Teams invitation MSG file. The particular MSG file that fails for me contains 5 recipients. We could share the file for investigation via email (we do not want to publicly expose it, as it may contain sensitive information).

**Expected behavior**
It should read the recipients and return a string.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser N/A
 - Version 5.5.5

**Comment by Sicos1977** [comment]
Please ZIP the file before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
No response... closed
