### ISSUE TITLE
StgOpenStorage() fails

### ISSUE THREAD

**Issue by fdncred** [Sicos1977/MSGReader#66]
After Patch Tuesday and Updating to VS2017 15.3 I can't get StgOpenStorage() to even work. This code in Storage.cs returns a null fileStorage variable.
```cs
// Open and load IStorage from file
NativeMethods.IStorage fileStorage;
NativeMethods.StgOpenStorage(storageFilePath, null,
    accesMode | NativeMethods.STGM.SHARE_EXCLUSIVE, IntPtr.Zero, 0, out fileStorage);
```
It calls LoadStorage() and immediately throws and exception with "Storage can not be null".
```
   at MsgReader.Outlook.Storage.LoadStorage(IStorage storage) in C:\Projects\MailToText\MsgReader\Outlook\Storage.cs:line 234
   at MsgReader.Outlook.Storage.Message.LoadStorage(IStorage storage) in C:\Projects\MailToText\MsgReader\Outlook\Message.cs:line 1302
   at MsgReader.Outlook.Storage..ctor(String storageFilePath, FileAccess fileAccess) in C:\Projects\MailToText\MsgReader\Outlook\Storage.cs:line 141
   at MsgReader.Outlook.Storage.Message..ctor(String msgfile, FileAccess fileAccess) in C:\Projects\MailToText\MsgReader\Outlook\Message.cs:line 1259
   at MailToText.BaseClass.ConvertMsgToText(String inputFileName) in C:\Projects\MailToText\MailToText\BaseClass.cs:line 202
```
Any tips on how to debug this?

**Comment by fdncred** [comment]
Reboot seems to have fixed it. Not sure what happened.

**Comment by Sicos1977** [comment]
Another fix is on my todo list ... get rid of the IStorage interface and make use of OpenMCDF ... like the way I did with my MSGKit project. But time is the biggest problem :-)
